### ISSUE TITLE
Scheduled tasks

### ISSUE THREAD

**Issue by marcqualie** [marcqualie/ecsx#36]
We want to allow functionality like cron to trigger tasks on a schedule.

Extending the `run` code to be triggered via Cloudwatch events makes the most sense, to keep things simple and re-use as much as possible.

## Prposal

```yaml
# Run sync-accounts tasks every hour
tasks:
  sync-accounts:
    schedule: "0 * * * *"
```
