### ISSUE TITLE
Console as first class task

### ISSUE THREAD

**Issue by marcqualie** [marcqualie/ecsx#42]
Instead of having `consoleTask` in the cluster, the console should actually be defined specficially if people want that functionality.

This creates an isolated services and means we don't have to worry about fully loading in an application for console on some projects.

```yaml
tasks:
  console:
    <<: *web
    command: [ /bin/sh ]
```
